### ISSUE TITLE
Error: could not download chart: path "./charts/mendix-installer" not found

### ISSUE THREAD

**Issue by kyleliu2020** [aws-ia/terraform-aws-mendix-private-cloud#17]
When I run this as terraform module with the [Provision Instructions](https://registry.terraform.io/modules/aws-ia/mendix-private-cloud/aws/latest?tab=resources), it reports error:
│ Error: could not download chart: path "./charts/mendix-installer" not found
│ 
│   with module.mendix-private-cloud.helm_release.mendix_installer,
│   on .terraform/modules/mendix-private-cloud/main.tf line 168, in resource "helm_release" "mendix_installer":
│  168: resource "helm_release" "mendix_installer" {

Work around solution:
after update .terraform/modules/mendix-private-cloud/main.tf Line 170
from
  chart     = "./charts/mendix-installer"
to
  chart     = "**${path.module}**/charts/mendix-installer"
then the error disappear.

**Comment by geoffreymersch** [comment]
Hi @kyleliu2020, thank for finding out this. Created this PR https://github.com/aws-ia/terraform-aws-mendix-private-cloud/pull/18 to fix this issue.
